# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarPal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarPal
 pod 'Alamofire'
 pod 'SwiftyJSON'
 pod 'GoogleMaps'
 pod 'GooglePlaces'



  target 'CarPalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarPalUITests' do
    # Pods for testing
  end

end
